server:
  port: 8080
  mode: debug # 运行模式：debug, release, test

database:
  driver: mysql
  host: localhost
  port: 3306
  username: root
  password: password
  dbname: cloud_eye
  charset: utf8mb4
  maxIdleConns: 10
  maxOpenConns: 100
  logLevel: info # 日志级别：silent, error, warn, info

log:
  level: debug # 日志级别：debug, info, warn, error, dpanic, panic, fatal
  format: json # 日志格式：json, console
  output: stdout # 日志输出位置：stdout, 或文件路径
  filename: logs/cloud-eye.log # 当output不是stdout时的文件路径

excel:
  importPath: ./uploads/import
  exportPath: ./uploads/export